POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlyYWEiLCJpZCI6IjVmYzRhMmYyOWU3MWZiMzk0NGEzYzM2MCIsImlhdCI6MTYwNjcyMjMwNX0.dhhet_HB4xFUocDgfCqprHVyPxcgGJB-Ga-3Wq2cQtQ

{
    "title": "Tips for life",
    "author": "Kalevi",
    "url": "www.kalevi.fi",
    "likes": "1"
}