PUT http://localhost:3003/api/blogs/5fb761ffc000a229944f9750
Content-Type: application/json

{
    "title": "The playbook - Art of getting females",
    "author": "Väinö Tuuli",
    "url": "www.väpä69.fi",
    "likes": "1",
    "id": "5fb761ffc000a229944f9750"
}